import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import Header from "../components/header/Header";
import BannerSection from "../components/bannerSection/BannerSection";
import AboutUsSection from "../components/aboutUsSection/AboutUsSection";
import ProgrammingTechnologiesSection from "../components/programmingTechnologiesSection/ProgrammingTechnologiesSection";
import StepsSection from "../components/stepsSection/StepsSection";
import QuestionsSection from "../components/questionSection/QuestionsSection";
import ReviewSection from "../components/review_/ReviewSection";
import GallerySection from "../components/gallerySection/GallerySection";
import ContactSection from "../components/contactSection/ContactSection";
import Footer from "../components/footer/Footer";

export default function Home() {
  const aboutUsSectionRef =
    React.useRef() as React.MutableRefObject<HTMLElement>;
  const progTechSectionRef =
    React.useRef() as React.MutableRefObject<HTMLElement>;
  const stepsSectionRef = React.useRef() as React.MutableRefObject<HTMLElement>;
  const questionsSectionRef =
    React.useRef() as React.MutableRefObject<HTMLElement>;
  const reviewsSectionRef =
    React.useRef() as React.MutableRefObject<HTMLElement>;
  const gallerySectionRef =
    React.useRef() as React.MutableRefObject<HTMLElement>;
  const contactSectionRef =
    React.useRef() as React.MutableRefObject<HTMLElement>;

  return (
    <>
      <Head>
        <title>Test Exercise </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <div className={styles.outerBlock}>
          <Header
            aboutUsSectionRef={aboutUsSectionRef}
            progTechSectionRef={progTechSectionRef}
            stepsSectionRef={stepsSectionRef}
            questionsSectionRef={questionsSectionRef}
            contactSectionRef={contactSectionRef}
          />

          <section id={styles.bannerSection}>
            <BannerSection />
          </section>

          <section ref={aboutUsSectionRef} id={styles.aboutUsSection}>
            <AboutUsSection />
          </section>

          <section ref={progTechSectionRef} id={styles.progTechSection}>
            <ProgrammingTechnologiesSection />
          </section>

          <section ref={stepsSectionRef} id={styles.stepsSection}>
            <StepsSection />
          </section>

          <section ref={questionsSectionRef} id={styles.questionsSection}>
            <QuestionsSection />
          </section>

          <section ref={reviewsSectionRef} id={styles.reviewsSection}>
            <ReviewSection />
          </section>

          <section ref={gallerySectionRef} id={styles.gallerySection}>
            <GallerySection />
          </section>

          <section ref={contactSectionRef} id={styles.contactSection}>
            <ContactSection />
          </section>

          <Footer
            aboutUsSectionRef={aboutUsSectionRef}
            stepsSectionRef={stepsSectionRef}
            questionsSectionRef={questionsSectionRef}
            reviewsSectionRef={reviewsSectionRef}
            gallerySectionRef={gallerySectionRef}
          />
        </div>
      </main>
    </>
  );
}
